POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "User Test",
    "username" : "illios 3",
    "password" : "123",
    "confPassword" : "123",
    "email" : "daffa2@gmail.com",
    "no_telp" : "082286541161"
} 


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{     
    "email" : "daffa2@gmail.com",
    "password" : "123"
} 
